networks:
  web_project.net:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./:/var/php
    working_dir: /var/php
    networks:
      - web_project.net
    depends_on:
      - database.db

  database.db:
    image: 'mariadb:latest'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - web_project.net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always

  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    networks:
      - web_project.net
